# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import random

### Step 2. Create 3 differents Series, each of length 100, as follows: 
1. The first a random number from 1 to 4 
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
first = pd.Series(random.choices(range(1, 5), k=100))
second = pd.Series(random.choices(range(1, 4), k=100))
third = pd.Series(random.choices(range(10000, 30001), k=100))

print(first)
print("----------------")
print(second)
print("----------------")
print(third)

0     2
1     2
2     3
3     2
4     4
     ..
95    1
96    2
97    3
98    3
99    3
Length: 100, dtype: int64
----------------
0     3
1     2
2     2
3     2
4     2
     ..
95    2
96    3
97    2
98    1
99    1
Length: 100, dtype: int64
----------------
0     26569
1     24764
2     21390
3     26656
4     18235
      ...
95    10566
96    11824
97    16174
98    24457
99    24443
Length: 100, dtype: int64

### Step 3. Let's create a DataFrame by joinning the Series by column

In [3]:
joining_all_column = pd.concat([first, second, third], axis=1)
joining_all_column.head(5)

   0  1      2
0  2  3  26569
1  2  2  24764
2  3  2  21390
3  2  2  26656
4  4  2  18235

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [4]:
joining_all_column = joining_all_column.set_axis(['bedrs','bathrs', 'price_sqr_meter'], axis=1)
joining_all_column.head(5)

   bedrs  bathrs  price_sqr_meter
0      2       3            26569
1      2       2            24764
2      3       2            21390
3      2       2            26656
4      4       2            18235

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [5]:
bigcolumn = pd.concat([first, second, third], axis=0)
bigcolumn

0         2
1         2
2         3
3         2
4         4
      ...
95    10566
96    11824
97    16174
98    24457
99    24443
Length: 300, dtype: int64

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [6]:
print(bigcolumn.index)
print(bigcolumn.index[-1] == 99)

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       ...
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
      dtype='int64', length=300)
True

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [7]:
bigcolumn = bigcolumn.reset_index(drop=True)
bigcolumn.reindex(list(range(300)))

0          2
1          2
2          3
3          2
4          4
       ...
295    10566
296    11824
297    16174
298    24457
299    24443
Length: 300, dtype: int64