# Getting Financial Data - Pandas Datareader (part b)

### Introduction:

This time you will get data from a website.


### Step 1. Import the necessary libraries

In [234]:
import pandas as pd
import datetime
import pandas_datareader # Didn't work
import yfinance as yf # Worked

### Step 2. Create your time range (start and end variables). The start date should be 01/01/2015 and the end should today (whatever your today is).

In [235]:
start_date = datetime.datetime(2015, 1, 1)
end_date = datetime.datetime.today()

### Step 3. Get an API key for one of the APIs that are supported by Pandas Datareader, preferably for AlphaVantage.

If you do not have an API key for any of the supported APIs, it is easiest to get one for [AlphaVantage](https://www.alphavantage.co/support/#api-key). (Note that the API key is shown directly after the signup. You do *not* receive it via e-mail.)

(For a full list of the APIs that are supported by Pandas Datareader, [see here](https://pydata.github.io/pandas-datareader/readers/index.html). As the APIs are provided by third parties, this list may change.)

### Step 4. Use Pandas Datarader to read the daily time series for the Apple stock (ticker symbol AAPL) between 01/01/2015 and today, assign it to df_apple and print it.

In [236]:
# Didn't work - required premium subscription

# df_apple = pandas_datareader.data.DataReader(
#     "AAPL",
#     "av-daily",
#     start=start_date,
#     end=end_date,
#     api_key="7P4SQK5QE1TYNUMV"
# ).read()

# print(df_apple)

# yf got me different data somehow

df_apple = yf.download("AAPL", start=start_date, end=end_date)
df_apple.columns = [col[0] for col in df_apple.columns]  # keep only the first level (isinstance(df_apple.columns, pd.MultiIndex) = True)

df_apple

[*********************100%***********************]  1 of 1 completed

                 Close        High         Low        Open     Volume
Date
2015-01-02   24.214891   24.682224   23.776352   24.671149  212818400
2015-01-05   23.532722   24.064285   23.346676   23.984551  257142000
2015-01-06   23.534939   23.794075   23.173918   23.596954  263188400
2015-01-07   23.864952   23.964619   23.632393   23.743135  160423600
2015-01-08   24.781893   24.839479   24.075357   24.192745  237458000
...                ...         ...         ...         ...        ...
2026-03-17  254.229996  255.130005  252.179993  252.960007   32361600
2026-03-18  249.940002  254.940002  249.000000  252.630005   35757900
2026-03-19  248.960007  251.830002  247.300003  249.399994   34864100
2026-03-20  247.990005  249.199997  246.000000  247.979996   88268000
2026-03-23  252.100006  254.559998  250.279999  253.990005   25819863

[2821 rows x 5 columns]

### Step 5. Add a new column "stock" to the dataframe and add the ticker symbol

In [237]:
df_apple["stock"] = "AAPL"
df_apple

                 Close        High         Low        Open     Volume stock
Date
2015-01-02   24.214891   24.682224   23.776352   24.671149  212818400  AAPL
2015-01-05   23.532722   24.064285   23.346676   23.984551  257142000  AAPL
2015-01-06   23.534939   23.794075   23.173918   23.596954  263188400  AAPL
2015-01-07   23.864952   23.964619   23.632393   23.743135  160423600  AAPL
2015-01-08   24.781893   24.839479   24.075357   24.192745  237458000  AAPL
...                ...         ...         ...         ...        ...   ...
2026-03-17  254.229996  255.130005  252.179993  252.960007   32361600  AAPL
2026-03-18  249.940002  254.940002  249.000000  252.630005   35757900  AAPL
2026-03-19  248.960007  251.830002  247.300003  249.399994   34864100  AAPL
2026-03-20  247.990005  249.199997  246.000000  247.979996   88268000  AAPL
2026-03-23  252.100006  254.559998  250.279999  253.990005   25819863  AAPL

[2821 rows x 6 columns]

### Step 6. Repeat the two previous steps for a few other stocks, always creating a new dataframe: Tesla, IBM and Microsoft. (Ticker symbols TSLA, IBM and MSFT.)

In [238]:
# Tesla

df_tesla = yf.download("TSLA", start=start_date, end=end_date)
df_tesla.columns = [col[0] for col in df_tesla.columns]
df_tesla["stock"] = "TSLA"

# IBM

df_ibm = yf.download("IBM", start=start_date, end=end_date)
df_ibm.columns = [col[0] for col in df_ibm.columns]
df_ibm["stock"] = "IBM"

# Microsoft

df_microsoft = yf.download("MSFT", start=start_date, end=end_date)
df_microsoft.columns = [col[0] for col in df_microsoft.columns]
df_microsoft["stock"] = "MSFT"

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

### Step 7. Combine the four separate dataFrames into one combined dataFrame df that holds the information for all four stocks

In [239]:
df = pd.concat([df_apple, df_tesla, df_ibm, df_microsoft])
df

                 Close        High         Low        Open     Volume stock
Date
2015-01-02   24.214891   24.682224   23.776352   24.671149  212818400  AAPL
2015-01-05   23.532722   24.064285   23.346676   23.984551  257142000  AAPL
2015-01-06   23.534939   23.794075   23.173918   23.596954  263188400  AAPL
2015-01-07   23.864952   23.964619   23.632393   23.743135  160423600  AAPL
2015-01-08   24.781893   24.839479   24.075357   24.192745  237458000  AAPL
...                ...         ...         ...         ...        ...   ...
2026-03-17  399.410004  404.399994  397.750000  400.269989   26228300  MSFT
2026-03-18  391.790009  398.000000  391.000000  397.130005   25908500  MSFT
2026-03-19  389.019989  392.489990  387.059998  390.100006   25138800  MSFT
2026-03-20  381.869995  387.000000  380.119995  386.790009   50771400  MSFT
2026-03-23  383.440002  387.209991  381.679993  383.994995   20140367  MSFT

[11284 rows x 6 columns]

### Step 8. Shift the stock column into the index (making it a multi-level index consisting of the ticker symbol and the date).

In [240]:
df = df.set_index([df.index, df["stock"]])
del df["stock"]

### Step 7. Create a dataFrame called vol, with the volume values.

In [241]:
vol = df[["Volume"]]
vol

                     Volume
Date       stock
2015-01-02 AAPL   212818400
2015-01-05 AAPL   257142000
2015-01-06 AAPL   263188400
2015-01-07 AAPL   160423600
2015-01-08 AAPL   237458000
...                     ...
2026-03-17 MSFT    26228300
2026-03-18 MSFT    25908500
2026-03-19 MSFT    25138800
2026-03-20 MSFT    50771400
2026-03-23 MSFT    20140367

[11284 rows x 1 columns]

### Step 8. Aggregate the data of volume to weekly.
Hint: Be careful to not sum data from the same week of 2015 and other years.

In [242]:
grouping_by_week = df.groupby(["stock", pd.Grouper(level=0, freq="W")]).sum()
grouping_by_week

                        Close         High          Low         Open  \
stock Date
AAPL  2015-01-04    24.214891    24.682224    23.776352    24.671149
      2015-01-11   120.522976   121.745569   118.638141   120.472034
      2015-01-18   120.062271   122.604911   119.174120   121.838575
      2015-01-25    98.261578    98.837435    96.571648    97.309192
      2015-02-01   127.045668   129.380115   126.146440   128.130940
...                       ...          ...          ...          ...
TSLA  2026-03-01  2037.699982  2062.790009  2005.600006  2036.300018
      2026-03-08  2003.970001  2020.179993  1961.850006  1983.200012
      2026-03-15  1991.950012  2031.260010  1966.339996  1998.899994
      2026-03-22  1935.869965  1974.080017  1922.920013  1958.029999
      2026-03-29   381.149994   385.329987   372.730011   373.084991

                      Volume
stock Date
AAPL  2015-01-04   212818400
      2015-01-11  1133010000
      2015-01-18  1216906400
      2015-01-25   794948000
      2015-02-01  1863370800
...                      ...
TSLA  2026-03-01   293561800
      2026-03-08   301991600
      2026-03-15   308315400
      2026-03-22   301189900
      2026-03-29    65174037

[2348 rows x 5 columns]

### Step 9. Find all the volume traded in the year of 2015

In [243]:
grouping_by_year = grouping_by_week.groupby(["stock", pd.Grouper(level=1, freq="YE")]).sum()

rows_list = []
for i in range(len(grouping_by_year.index)):
    if grouping_by_year.index[i][1].year == 2015:
        rows_list.append(i)
rows_list

final_answer = grouping_by_year.iloc[rows_list, :]["Volume"].reset_index()

del final_answer["Date"]
final_answer["Year"] = "2015"

final_answer

  stock       Volume  Year
0  AAPL  51769153600  2015
1   IBM   1142278025  2015
2  MSFT   8960227600  2015
3  TSLA  16162459500  2015